"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const encapsulamiento_1 = require("./encapsulamiento");
const herencia_1 = require("./herencia");
const polimorfismo_1 = require("./polimorfismo");
console.log(encapsulamiento_1.Usuario.saludar());
const persona = new encapsulamiento_1.Persona('Carlos', 30, 'Masculino');
console.log(`Persona: ${persona.getNombre()}, ${persona.getEdad()} años, de genero ${persona.sexo}`);
const estudiante = new herencia_1.Estudiante('Ana', 22, 'Masculino', '2022001');
console.log(`Estudiante: ${estudiante.getNombre()}, ${estudiante.getEdad()} años, Matrícula: ${estudiante.getMatricula()} de genero ${estudiante.sexo}`);
const profesor = new polimorfismo_1.Profesor('Luis', 40, 'Masculino', 'Matemáticas');
console.log(`Profesor: ${profesor.getNombre()}, ${profesor.getEdad()} años, Materia: ${profesor.getMateria()}, de genero ${profesor.sexo}`);
const human = new encapsulamiento_1.Persona('Alex', 23, 'Masculino');
console.log(`Persona: ${human.nombre}, ${human.getEdad()} años, de genero ${human.sexo}`);
const admin = new herencia_1.Admin('María', 35, 'Femenino', ['Gestionar usuarios', 'Configurar sistema']);
console.log(admin.describir());
admin.agregarPermiso('Auditor');
console.log(admin.mostrarPermisos());
console.log((0, polimorfismo_1.presentarPersona)(persona));
console.log((0, polimorfismo_1.presentarPersona)(estudiante));
console.log((0, polimorfismo_1.presentarPersona)(profesor));
console.log((0, polimorfismo_1.presentarPersona)(human));
